name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/ssh-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        fingerprint: ${{ secrets.FINGERPRINT }}
        passphrase: ${{ secrets.PASSPHRASE }}
      with:
        source: "."
        target: "/data/www/default"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        fingerprint: ${{ secrets.FINGERPRINT }}
        script: ls